/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TCPClient.java
 *
 * Created on 28 Μαρ 2012, 1:54:33 μμ
 */
package tcpclient;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;

/**
 * Dhmioyrgia ths klashs TCPClient. Prokeitai gia enan client me grafiko perivallon poy leitoyrgei symfwna me to 
 * protokolo TCP kai antallazei mhnhmata me allous idious clients mesw enos server.
 */
public class TCPClient extends javax.swing.JFrame {

    //Dhlwsh enos socket se TCP.
    private Socket socket;
    //Dhlwsh toy reader ths eiserxomenhs rohs ths syndeshs.
    private BufferedReader inputReader;
    //Dhlwsh toy writer ths ekserxomenhs rohs ths syndeshs.
    private PrintWriter outputWriter;

    /** Creates new form TCPClient */
    public TCPClient() {
    
        //Kalei thn me8odo poy ftiaxnei to User Interface
        initComponents(); 
        jToggleButton2.setEnabled(false);
    }

    /*
     * Me8odos poy dhmioyrgei thn syndesh me ton server, ta kanalia rohs kai epeita diavazei eiserxomena mhnhmata.
     */
    private void connectToServer() {

        //H IP diey8ynsh toy server. Thn diavazei apo to UI.
        String serverIPAddress = jTextField3.getText();
        //H porta pou afoygrazetai o server. Thn diavazei apo to UI.
        int serverPort = Integer.parseInt(jTextField4.getText());

        //Ean to socket den yparxei dhmioyrghse to.
        if (socket == null) {
            //Xrhsh enos handler gia unknown host exceptions(p.x. la8os ip) 
            //kai ioexceptions(p.x. problhma sthn roh dedomenwn)
            try {

                //Dhmiourgia enos socket se TCP to opoio 8a kanei aithsh gia syndesh ston server(sygkekrimenh IP kai porta)
                //kai an autos thn kanei dekth 8a dhmioyrgh8ei h SYNDESH.
                socket = new Socket(InetAddress.getByName(serverIPAddress), serverPort);

            } catch (UnknownHostException ex) {
             
            } catch (IOException ex) {
                
            }catch (Exception ex) {
                
            }
        }

        //Xrhsh enos handler gia ioexceptions(p.x. problhma sthn roh dedomenwn).
        try {

            //Reader ths eiserxomenhs rohs ths syndeshs gia thn anagnwsh mhmhmatwn.
           inputReader = new BufferedReader(new InputStreamReader(socket.getInputStream()));

            //Writer sthn ekserxomenh roh ths syndeshs gia thn apostolh mhnhmatwn.
            outputWriter = new PrintWriter(socket.getOutputStream(), true);

        } catch (IOException e) {
            e.printStackTrace();
        }

        //Kalei thn me8odo receiveData gia na lanbanei mhnhmata se neo thread.
        new Thread() {

            @Override
            public void run() {
                receiveData();
            }
        }.start();
    }

    /*
     * Me8odos poy diavazei ta eiserxomena mhnhmata se mia TCP syndesh poy exei dhmioyrgh8ei me enan server. 
     */
    private void receiveData() {

        //Xrhsh enos handler gia ioexceptions(p.x. problhma sthn roh dedomenwn).
        try {

            //Epanalhptikh anagnvsh mhmhmatwn apo thn eiserxomenh roh ths syndeshs.
            while (true) {
               
                  //Eiserxomeno mhnhma(anagnwsh apo thn roh mesw tou reader).
                String receivedMessage = inputReader.readLine();
                //Emfanish toy eiserxomenou mhnhmatos sto textarea toy client.
                if (receivedMessage==null) {
                    return;
                }
             
                jTextArea1.append(receivedMessage + "\n");
                if(receivedMessage.equalsIgnoreCase(" choose another nickname")){
                    System.out.println("isss ignore care");
                jToggleButton2.setEnabled(false);
     jToggleButton1.setEnabled(true);
                }
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /*
     * Me8odos gia thn apostolh mhnhmatos se mia TCP syndesh poy exei dhmioyrgh8ei me enan server.
     */
    private void sendData(String messageToSend) {

        //Apostolh toy mhnhmatos(eggrafh toy mhnhmatos sthn roh mesw tou writer).
        outputWriter.println(messageToSend);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Server Data"));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("IP Address  ");
        jPanel5.add(jLabel1);

        jTextField3.setText("127.0.0.1");
        jPanel5.add(jTextField3);

        jLabel2.setText("    Port  ");
        jPanel5.add(jLabel2);

        jTextField4.setText("15000");
        jPanel5.add(jTextField4);

        getContentPane().add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255)), "Client"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Username"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(jTextField1);

        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setText("Sign in");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1);

        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setSelected(true);
        jToggleButton2.setText("Sign out");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton2);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Messages"));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Send Message"));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        jTextField2.setColumns(50);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField2);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);

        jTextField5.setColumns(12);
        jPanel4.add(jTextField5);

        jSeparator2.setForeground(new java.awt.Color(240, 240, 240));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator2);

        jSeparator1.setForeground(new java.awt.Color(153, 0, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel4.add(jSeparator1);

        jButton2.setText("Users");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

    //Klhsh ths me8odoy poy kanei thn syndesh me ton server.
    connectToServer();
    //Klhsh ths me8odou gia apostolh mhnhmatos.
    sendData("SignIn:" + jTextField1.getText());
jToggleButton2.setEnabled(true);
     jToggleButton1.setEnabled(false);
}//GEN-LAST:event_jToggleButton1ActionPerformed

private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed

    //Klhsh ths me8odou gia apostolh mhnhmatos.
    sendData("Signout");
  jToggleButton2.setEnabled(false);
     jToggleButton1.setEnabled(true);
}//GEN-LAST:event_jToggleButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //Elegxos an yparxei onoma sto pedio gia prosopikh apostolh
    if (jTextField5.getText().equals("")) {
        //Klhsh ths me8odou gia apostolh mhnhmatos.
        sendData("Message:" + jTextField2.getText());
        //Svhsimo toy keimenoy apo to textField.
        jTextField2.setText("");
    } else {
        //Klhsh ths me8odou gia apostolh mhnhmatos.
        sendData("MessageTo:" + jTextField5.getText() + ":" + jTextField2.getText());
        //Svhsimo toy keimenoy apo ta textFields.
        jTextField2.setText("");
        jTextField5.setText("");
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    //Klhsh ths me8odou gia apostolh mhnhmatos.
    sendData("Users");

}//GEN-LAST:event_jButton2ActionPerformed

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
    //Elegxos an yparxei onoma sto pedio gia prosopikh apostolh
    if (jTextField5.getText().equals("")) {
        //Klhsh ths me8odou gia apostolh mhnhmatos.
        sendData("Message:" + jTextField2.getText());
        //Svhsimo toy keimenoy apo to textField.
        jTextField2.setText("");
    } else {
        //Klhsh ths me8odou gia apostolh mhnhmatos.
        sendData("MessageTo:" + jTextField5.getText() + ":" + jTextField2.getText());
        //Svhsimo toy keimenoy apo ta textFields.
        jTextField2.setText("");
        jTextField5.setText("");
    }
}//GEN-LAST:event_jTextField2ActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    if (socket != null) {
        try {
            socket.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCPClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCPClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCPClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCPClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TCPClient client = new TCPClient();
                client.setSize(600, 700);
                client.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
